### PR TITLE
Add possibility for add env files based on $DOCKSAL_ENVIRONMENT

### PR DESCRIPTION
**Pull request by b-connect**
Pull request for #352

### CODE REVIEW

**Comment by achekulaev** [comment]
Thanks for the PR! Looks good to me. Great job figuring out how the code is set up in that function @b-connect!

**Comment by lmakarov** [comment]
Also, `DOCKSAL_ENVIRONMENT` variable should be printed in `config_show` (above the `PROJECT_ROOT` will be fine).

**Comment by b-connect** [comment]
If we remove docksal-local.env this is a breaking change.

**Comment by b-connect** [comment]
Also i want to have a local.env file od docksal-local.env file.

Why.

We use docksal also for staging and dev systems. We need a possibility to have many instances of a staging system (ex PR Builds).

I would prefer following solution of a loading order

- docksal.env ( in vcs)
- docksal.${DOCKSAL_ENVIRONMENT}.env (in vcs )
- local.env ( not in vcs )

**Comment by b-connect** [comment]
Added output for config_show

**Comment by lmakarov** [comment]
> If we remove docksal-local.env this is a breaking change.

Not at all. 

> `DOCKSAL_ENVIRONMENT="${DOCKSAL_ENVIRONMENT:-local}"`

`local` is just one of the environments and it is set by default. `docksal-local.env` is expected to be gitignored. Same for `docksal-local.yml`.

Switching to a different environment file  is done via setting/passing the `DOCKSAL_ENVIRONMENT` variable. Those files would be committed into the repo.

The result is pretty much identical to what you are looking for with the least amount of changes to fin:

```
docksal.env ( in vcs)
docksal-${DOCKSAL_ENVIRONMENT}.env (in vcs )
docksal-local.env ( not in vcs )
```

> We use docksal also for staging and dev systems. We need a possibility to have many instances of a staging system (ex PR Builds).

We use Docksal internally for locals and for sandboxes (branch/PR builder) as well. In those environments `docksal-local.env` is generated and holds the necessary CI setting overrides.

**Comment by b-connect** [comment]
So we should remove docksal-local.env at all ?

**Comment by lmakarov** [comment]
If by "remove" you mean removing `docksal-local.env` from the project repo, then yes. It is not supposed to go there. I realized we do not have this covered in the docs (will update), but the sample projects explain it well - https://github.com/docksal/drupal8/blob/master/.docksal/docksal.env#L1-L4

**Pull request closed without merging**
