### PR TITLE
Fix the bug that virtualbox update breaks docker-machine upgrade.

### LINKED ISSUE #280: VirtualBox update breaks docker-machine update when run within one update cycle
To upgrade VM it should be running. Update function checks for this. But when VirtualBox is being installed during update then it stops the VM. So if both VM upgrade and VBox upgrade were required it will fail because VM will not be running for VM upgrade. 

```
All running projects will be stopped for vm upgrade. Continue? [y/n]: y
[!] Using Docksal version: develop
Updating fin... 1.13.0 [OK]
Updating stack files...
services.yml
stack-acquia.yml
stack-acquia-static.yml
stack-default.yml
stack-default-static.yml
volumes-bind.yml
volumes-nfs.yml
volumes-unison.yml
VirtualBox version should be 5.1.22 or higher
Do you want to download VirtualBox 5.1.22 to '/Users/alexei.chekulaev/Downloads/VirtualBox-5.1.22-115126-OSX.dmg' and install it? [y/n]: y
######################################################################## 100.0%

Attaching /Users/alexei.chekulaev/Downloads/VirtualBox-5.1.22-115126-OSX.dmg

Please finish VirtualBox installation and press ENTER to continue (Ctrl+C to exit)...Please finish VirtualBox installation and press ENTER to continue (Ctrl+C to exit)...

Installing docker client v17.06.0-ce...
Downloading docker-17.06.0-ce.tgz...
######################################################################## 100.0%
Installing docker-compose v1.14.0...
Downloading docker-compose-Darwin-x86_64...
######################################################################## 100.0%
Installing docker-machine v0.12.0...
Downloading docker-machine-Darwin-x86_64...
######################################################################## 100.0%
Preparing to update virtual machine...
Stopping "docksal"...
Machine "docksal" is already stopped.
Updating system images...
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at tcp://192.168.64.100:2376. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at tcp://192.168.64.100:2376. Is the docker daemon running?
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at tcp://192.168.64.100:2376. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
```

### PR DESCRIPTION
**Pull request by achekulaev**
Fixes #280

### CODE REVIEW

**Comment by achekulaev** [comment]
This one needs testing @lmakarov . I don't have any VM alive to test right now.

**Comment by lmakarov** [comment]
Tested on a Mac VM.

Install

```
OSXs-Mac:~ osxuser$ curl -sSLk https://get.docksal.io | bash
Password:
Updating fin... 1.27.0 [OK]
Updating stack files...
services.yml
stack-acquia.yml
stack-acquia-static.yml
stack-default.yml
stack-default-static.yml
volumes-bind.yml
volumes-nfs.yml
volumes-unison.yml
VBoxManage binary was not found
Downloading and installing VirtualBox 5.1.22
######################################################################## 100.0%
Attaching /Users/osxuser/Downloads/VirtualBox-5.1.22-115126-OSX.dmg

Please finish VirtualBox installation using installer (Ctrl+C to exit)...
Installing docker client v17.06.0-ce...
Downloading docker-17.06.0-ce.tgz...
######################################################################## 100.0%
Installing docker-compose v1.14.0...
Downloading docker-compose-Darwin-x86_64...
######################################################################## 100.0%
Installing docker-machine v0.12.2...
Downloading docker-machine-Darwin-x86_64...
######################################################################## 100.0%
Update finished
OSXs-Mac:~ osxuser$ fin vm start
Creating docker machine 'docksal'...
Creating CA: /Users/osxuser/.docker/machine/certs/ca.pem
Creating client certificate: /Users/osxuser/.docker/machine/certs/cert.pem
Running pre-create checks...
(docksal) Image cache directory does not exist, creating it at /Users/osxuser/.docker/machine/cache...
Creating machine...
(docksal) Downloading /Users/osxuser/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v17.06.0-ce/boot2docker.iso...
(docksal) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(docksal) Creating VirtualBox VM...
(docksal) Creating SSH key...
(docksal) Starting the VM...
(docksal) Check network to re-create if needed...
(docksal) Found a new host-only adapter: "vboxnet0"
(docksal) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env docksal
docksal is already active
Pulling Docksal system images...
1.1: Pulling from docksal/vhost-proxy
90f4dba627d6: Pull complete 
64f3429bec48: Pull complete 
c9144e91faa4: Pull complete 
b51b8990920f: Pull complete 
5b574e44e8e3: Pull complete 
8f979b3e8a0f: Pull complete 
ad288c99f10b: Pull complete 
e0a701950d42: Pull complete 
f89aeb29e287: Pull complete 
9f16a27b9315: Pull complete 
78b2ae800114: Pull complete 
dfca5973bddb: Pull complete 
3e929b6ab30c: Pull complete 
fb5fc0609d1a: Pull complete 
ae087c4e7dbe: Pull complete 
Digest: sha256:06d473ddcb56d0e55d6c3e00dcacb5cd5c9599e189da88fd3a36f7bbe779c503
Status: Downloaded newer image for docksal/vhost-proxy:1.1
1.0: Pulling from docksal/dns
b7f33cc0b48e: Pull complete 
091c4c1a4aed: Pull complete 
87aafca09b0e: Pull complete 
484f9c5a06d2: Pull complete 
b10e71c13bee: Pull complete 
86e439a97925: Pull complete 
ed8e54398806: Pull complete 
Digest: sha256:558677fb299e2002b05f2d8e6c950b75ea84e55cab788922b1372d39fe86b2a1
Status: Downloaded newer image for docksal/dns:1.0
1.0: Pulling from docksal/ssh-agent
b7f33cc0b48e: Already exists 
4ab503591894: Pull complete 
c74fcee68210: Pull complete 
Digest: sha256:c72983e4d2efab289f48f2fee654930c40c74cbce14eb504055718ad3797292c
Status: Downloaded newer image for docksal/ssh-agent:1.0
Resetting network settings...
Resetting Docksal services...
 * proxy
 * dns and resolver for .docksal domain
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
lstat /Users/osxuser/.ssh: no such file or directory
Configuring NFS shares...
Writing /etc/exports...
Starting nfsd...
Starting the nfsd service
Mounting NFS shares...
Starting nfs client utilities.
Mounting local /Users to /Users
Importing ssh keys...
lstat /Users/osxuser/.ssh: no such file or directory
```

Update - 1st pass: did not fail, but did not update VirtualBox

```
OSXs-Mac:~ osxuser$ DOCKSAL_VERSION=feature/fix-update-virtualbox fin update
[!] Using Docksal version: feature/fix-update-virtualbox
Updating fin...
fin One second! Checking for updates...
1.32.0 downloaded...
[STEP 2/6] Updating stack files...
services.yml
stack-acquia.yml
stack-acquia-static.yml
stack-default.yml
stack-default-static.yml
volumes-bind.yml
volumes-nfs.yml
volumes-unison.yml
[STEP 3/6] Updating tools...
Installing docker client v17.09.0-ce...
Downloading docker-17.09.0-ce.tgz...
######################################################################## 100.0%
Installing docker-compose v1.17.1...
Downloading docker-compose-Darwin-x86_64...
######################################################################## 100.0%
Installing docker-machine v0.13.0...
Downloading docker-machine-Darwin-x86_64...
######################################################################## 100.0%
Preparing to update virtual machine...
Stopping "docksal"...
Machine "docksal" was stopped.
Downloading boot2docker.iso v17.09.0-ce
######################################################################## 100.0%
Starting "docksal"...
(docksal) Check network to re-create if needed...
(docksal) Waiting for an IP...
Machine "docksal" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
Configuring NFS shares...
NFS shares are already configured
Mounting NFS shares...
Starting nfs client utilities.
Mounting local /Users to /Users
Importing ssh keys...
[STEP 4/6] Updating system images...
1.1: Pulling from docksal/vhost-proxy
Digest: sha256:06d473ddcb56d0e55d6c3e00dcacb5cd5c9599e189da88fd3a36f7bbe779c503
Status: Image is up to date for docksal/vhost-proxy:1.1
1.0: Pulling from docksal/dns
Digest: sha256:558677fb299e2002b05f2d8e6c950b75ea84e55cab788922b1372d39fe86b2a1
Status: Image is up to date for docksal/dns:1.0
1.0: Pulling from docksal/ssh-agent
Digest: sha256:c72983e4d2efab289f48f2fee654930c40c74cbce14eb504055718ad3797292c
Status: Image is up to date for docksal/ssh-agent:1.0
Resetting network settings...
Resetting Docksal services...
 * proxy
 * dns and resolver for .docksal domain
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
Checking for orphaned containers...
Removing dangling images...
Removing dangling volumes...
[STEP 5/6] Updating Docksal images
1.0: Pulling from docksal/dns
Digest: sha256:558677fb299e2002b05f2d8e6c950b75ea84e55cab788922b1372d39fe86b2a1
Status: Image is up to date for docksal/dns:1.0
1.0: Pulling from docksal/ssh-agent
Digest: sha256:c72983e4d2efab289f48f2fee654930c40c74cbce14eb504055718ad3797292c
Status: Image is up to date for docksal/ssh-agent:1.0
1.1: Pulling from docksal/vhost-proxy
Digest: sha256:06d473ddcb56d0e55d6c3e00dcacb5cd5c9599e189da88fd3a36f7bbe779c503
Status: Image is up to date for docksal/vhost-proxy:1.1
Update finished
```

Update - 2nd pass: asked for VirtualBox update, downloaded, started installation, failed. Apparently because the VM was not stopped prior to running the VBox update.

```
OSXs-Mac:~ osxuser$ DOCKSAL_VERSION=feature/fix-update-virtualbox fin update
VirtualBox version should be 5.1.28 or higher
Found VirtualBox 5.1.28 in '/Users/osxuser/Downloads/VirtualBox-5.1.28-117968-OSX.dmg'. Using it...
Attaching /Users/osxuser/Downloads/VirtualBox-5.1.28-117968-OSX.dmg

Please finish VirtualBox installation and press ENTER to continue (Ctrl+C to exit)...^C
```
http://take.ms/YVTuZ

**Comment by achekulaev** [comment]
> Update - 1st pass: did not fail, but did not update VirtualBox

As expected. Future updates should be fixed though. To test you need to self-update fin first and then run regular update. 

> Apparently because the VM was not stopped prior to running the VBox update.

Yeah this was the problem. Fixed now. 
So basically to test you need to 

```
DOCKSAL_VERSION=feature/fix-update-virtualbox fin update --self
DOCKSAL_VERSION=feature/fix-update-virtualbox fin update
```

Seems to be working here.

**Comment by achekulaev** [comment]
@lmakarov ping

**Pull request merged**
