### PR TITLE
Support entirely custom docker-compose configurations

### LINKED ISSUE #1425: Support entirely custom docker-compose configurations
Write documentation for entirely custom docker-compose stack configurations with Docksal.

The resulting project stack docker-compose config would then entirely depend on the contents of `.docksal/docksal.yml`.
Support for `docksal.env` and environment specific files would still work (e.g., `docksal-local.env`, `docksal-local.yml`).

### PR DESCRIPTION
**Pull request by lmakarov**
- Refactored stack configuration docs
- Renamed `DOCKSAL_VOLUMES=disable` to `DOCKSAL_VOLUMES=disabled`

Fixes #1425. Closes #1417.

### CODE REVIEW

**Comment by lmakarov** [comment]
I renamed `DOCKSAL_VOLUMES=disable` to `DOCKSAL_VOLUMES=disabled`.
This was never documented and likely not used by anyone, so should be safe to rename.

**Comment by lmakarov** [comment]
Pending documentation updates.

**Comment by lmakarov** [comment]
Made updates to the following sections in docs:

- https://deploy-preview-1426--docs-docksal-io.netlify.app/stack/understanding-stack-config/
- https://deploy-preview-1426--docs-docksal-io.netlify.app/stack/zero-configuration/
- https://deploy-preview-1426--docs-docksal-io.netlify.app/stack/custom-configuration/
- https://deploy-preview-1426--docs-docksal-io.netlify.app/service/db/postresql/

@shelane, @achekulaev please review.

**Comment by shelane** [comment]
You'd rather a separate page for postreSQL than the one on the service options?
https://docs.docksal.io/service/db/options/

**Comment by lmakarov** [comment]
@shelane Nope. Thanks's for catching this. I missed the existing PostgreSQL section in https://docs.docksal.io/service/db/options/. Dropped the redundant one.

**Review by shelane — APPROVED** [review]

**Pull request merged**
