### PR TITLE
Changing VSCode docs to reflect working launch.json.

### PR DESCRIPTION
**Pull request by JDDoesDev**
The recently committed documentation for VSCode Xdebug did not work on my install.  I have successfully been using Xdebug with VSCode for some time with these settings, so I recommend that we use this example instead of the current one.

### CODE REVIEW

**Comment by achekulaev** [comment]
@lmakarov do you have an idea why tests are failing on setting ENV variables?

**Comment by sean-e-dietrich** [comment]
@achekulaev I believe secrets are failing because it's a forked repo with the PR and the variables are marked as secret.

**Comment by lmakarov** [comment]
Tests will always fail with PRs since there are private ENV variables set in Travis, which are used in tests and which are not passed to PR builds. We'll need to refactor the builds/tests to only run PR-compatible tests on PR builds.

**Comment by sean-e-dietrich** [comment]
@JDDoesDev you are correct. Thanks!

**Pull request merged**
