### PR TITLE
Updated Travis Config to work with External PRs

### PR DESCRIPTION
**Pull request by sean-e-dietrich**
Modified the travis.yml file to account for external PRs

### CODE REVIEW

**Comment by sean-e-dietrich** [comment]
@achekulaev @lmakarov looks like I was able to get the tests running but now is failing for a different reason now.

**Comment by lmakarov** [comment]
The was an issue with one of the Ubuntu repos expired keys. I restarted the build to see if that helps.

**Comment by lmakarov** [comment]
Actually, there seem to be some connectivity issues, as I've just had a different issues with the Docker update script in another branch.

**Comment by lmakarov** [comment]
All good now. Thanks!

**Comment by achekulaev** [comment]
Thanks Sean!

**Pull request merged**
