### PR TITLE
Add redis service.

### PR DESCRIPTION
**Pull request by michael-molchanov**

### CODE REVIEW

**Comment by achekulaev** [comment]
LGTM

**Comment by sean-e-dietrich** [comment]
This looks good. I'd like to see if there is more of an ability to configure redis a little better. Using the standard redis image right now basically leaves no room for project configuration so for projects where they need to tune redis they can't do it.

**Comment by achekulaev** [comment]
Good point @sean-e-dietrich

**Comment by lmakarov** [comment]
Wait... We already have docs for using Redis here: https://docs.docksal.io/en/master/tools/redis/
We just need to choose which image to use as the default in the services.yml and update the docs respectively.

**Comment by achekulaev** [comment]
Closing in favor of https://github.com/docksal/docksal/issues/874

**Pull request closed without merging**
