### PR TITLE
fin share-v2 and cloudflared service

### PR DESCRIPTION
**Pull request by lmakarov**
Creates a temporary public URL for the project using a [free Cloudflare Tunnel](https://try.cloudflare.com/) ([formerly Argo Tunnel](https://developers.cloudflare.com/cloudflare-one/glossary#cloudflare-tunnel)).

This integration is implemented similar to the IDE integration.
`cloudflared` services runs as part of the project's Docker Compose stack.

It can be enabled via an environment variable:

```
❯ fin config set --env=local CLOUDFLARED_ENABLED=1
Added value for CLOUDFLARED_ENABLED into /Users/leonid/Work/Projects/test/.docksal/docksal-local.env

~/Work/Projects/test main*
❯ fin project start
Starting services...
test_db_1 is up-to-date
test_cli_1 is up-to-date
test_web_1 is up-to-date
Creating test_cloudflared_1 ... done
Project URL: http://test.docksal.site
```

It also can be managed via a dedicated `fin share-v2` command group:

```
❯ fin share-v2

Create a temporary public URL for the project using Cloudflare Argo Tunnel

Usage: share-v2 [command]

Commands:
  start                         Start tunnel and print public URL
  stop                          Stop tunnel
  status                        Prints tunnel status and public URL (if Active)
  url                           Prints tunnel public URL
  logs                          Prints tunnel container logs

Examples:
  fin share-v2 start            Start tunnel and print public URL
```

**To test**

```
DOCKSAL_VERSION=feature/share-v2 fin update
fin share-v2
```

**Demo**

[image](https://asciinema.org/a/429133)

Related to #1494

### CODE REVIEW

**Comment by lmakarov** [comment]
Sounds like Cloudflare Argo Tunnel is now just [Cloudflare Tunnel](https://www.cloudflare.com/en-gb/products/tunnel/) ([source](https://developers.cloudflare.com/cloudflare-one/glossary#cloudflare-tunnel)). That said, they still refer to it as Argo Tunnel pretty much everywhere...

I made text adjustments in code.

**Comment by lmakarov** [comment]
@achekulaev, @sean-e-dietrich, @lpeabody any objections to merging this?

We may also need docs (cc @shelane).

**Comment by sean-e-dietrich** [comment]
I like this as a solution as I was just testing `fin share` and looks like ngrok now requires people to sign up for an account.

I went to test this and got the following:

```
➜  test-share fin start
\e[0;32;49mStarting services...\e[0m
test-share_cli_1 is up-to-date
test-share_web_1 is up-to-date
\e[0;32;49mProject URL: \e[0;33;49mhttp://test-share.docksal\e[0m\e[0m
➜  test-share fin share-v2 start
Added value for CLOUDFLARED_ENABLED into /Users/sdietrich/projects/test-share/.docksal/docksal-local.env
\e[0;32;49mStarting services...\e[0m
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml

\e[0;32;49mPublic URL:\e[0m \e[0;33;49m\e[0m
```

I had a valid project started

```
➜  test-share fin config info
---------------------
COMPOSE_PROJECT_NAME_SAFE: test-share
COMPOSE_FILE:
/Users/sdietrich/.docksal/stacks/volumes-nfs.yml
/Users/sdietrich/.docksal/stacks/stack-default-nodb.yml
/Users/sdietrich/projects/test-share/.docksal/docksal.yml
/Users/sdietrich/.docksal/stacks/overrides-cloudflared.yml
ENV_FILE:
/Users/sdietrich/projects/test-share/.docksal/docksal.env
/Users/sdietrich/projects/test-share/.docksal/docksal-local.env

PROJECT_ROOT: /Users/sdietrich/projects/test-share
DOCROOT: docroot
VIRTUAL_HOST: test-share.docksal
VIRTUAL_HOST_ALIASES: *.test-share.docksal
IP: 192.168.64.100

MySQL endpoint:
Public URL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DEFAULT_VERSION: null
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: test-share.docksal
      GIT_USER_EMAIL: sean@kanopistudios.com
      GIT_USER_NAME: Sean Dietrich
      HOST_GID: '20'
      HOST_UID: '501'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_ACQUIACLI_KEY: null
      SECRET_ACQUIACLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: wk-wS*****xZjky
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: test-share.docksal
      XDEBUG_CONFIG: client_host=192.168.64.1 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    healthcheck:
      interval: 10s
    hostname: cli
    image: docksal/cli:php7.4-3.0
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /tmp/.docksal/test-share:/tmp/.docksal/test-share:ro
    - project_root:/var/www:rw,nocopy,cached
  cloudflared:
    command:
    - tunnel
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      NO_AUTOUPDATE: "true"
      TUNNEL_URL: http://web
    healthcheck:
      interval: 10s
    hostname: cloudflared
    image: cloudflare/cloudflared:2021.8.1
    logging:
      options:
        max-file: '10'
        max-size: 1m
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    healthcheck:
      interval: 10s
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/sdietrich/projects/test-share
      io.docksal.virtual-host: test-share.docksal,*.test-share.docksal,test-share.docksal.*
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '3.9'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/sdietrich/projects/test-share
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
```

**Comment by lmakarov** [comment]
@sean-e-dietrich pushes updates. Check now.

**Comment by lmakarov** [comment]
Just realized that this needs documentation.

**Comment by lmakarov** [comment]
Looks like `cloudflared` binary is [available for arm64](https://github.com/cloudflare/cloudflared/releases), but there is no official arm64 docker image - https://hub.docker.com/r/cloudflare/cloudflared/tags

Upstream issue : https://github.com/cloudflare/cloudflared/issues/237

There are a few unofficial multi-arch images:

- https://hub.docker.com/r/crazymax/cloudflared/tags
- https://hub.docker.com/r/raspbernetes/cloudflared/tags

I'll switch to one of the unofficial images to have `fin share-v2` available for M1/ARM64 users.

**Review by sean-e-dietrich — COMMENTED** [review]
I tested this out. The first time I run this on a new project I am unsuccessful. Once I restart then I can access the Cloudflare Tunnel

```
ubuntu@testdocksal:~/projects$ mkdir test; cd test; fin init
Initialize a project in /home/ubuntu/projects/test? [y/n]: y
DOCROOT has been detected as docroot. Is that correct? [y/n]: y
Configuration was generated. You can start it with fin project start
Removing containers...
[+] Running 1/0
 ⠿ test  Warning: No resource found to remove                                                                                                                                                                                                                                                 0.0s
Starting services...
[+] Running 7/7
 ⠿ Network test_default        Created                                                                                                                                                                                                                                                        0.1s
 ⠿ Volume "test_cli_home"      Created                                                                                                                                                                                                                                                        0.0s
 ⠿ Volume "test_project_root"  Created                                                                                                                                                                                                                                                        0.0s
 ⠿ Volume "test_db_data"       Created                                                                                                                                                                                                                                                        0.0s
 ⠿ Container test_db_1         Started                                                                                                                                                                                                                                                        3.9s
 ⠿ Container test_cli_1        Started                                                                                                                                                                                                                                                        3.7s
 ⠿ Container test_web_1        Started                                                                                                                                                                                                                                                        2.7s
Connected vhost-proxy to "test_default" network.
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Project URL: http://test.docksal
ubuntu@testdocksal:~/projects/test$ fin share-v2 start
Added value for CLOUDFLARED_ENABLED into /home/ubuntu/projects/test/.docksal/docksal-local.env
Starting services...
[+] Running 4/4
 ⠿ Container test_cloudflared_1  Started                                                                                                                                                                                                                                                      0.9s
 ⠿ Container test_db_1           Running                                                                                                                                                                                                                                                      0.0s
 ⠿ Container test_cli_1          Running                                                                                                                                                                                                                                                      0.0s
 ⠿ Container test_web_1          Running                                                                                                                                                                                                                                                      0.0s
Project URL: http://test.docksal
Public URL: https://audience-arrivals-pending-favorite.trycloudflare.com
ubuntu@testdocksal:~/projects/test$ fin restart
Disconnecting project network...
Stopping services...
[+] Running 4/4
 ⠿ Container test_web_1          Stopped                                                                                                                                                                                                                                                      1.3s
 ⠿ Container test_db_1           Stopped                                                                                                                                                                                                                                                      0.6s
 ⠿ Container test_cloudflared_1  Stopped                                                                                                                                                                                                                                                      0.0s
 ⠿ Container test_cli_1          Stopped                                                                                                                                                                                                                                                      0.3s
Starting services...
[+] Running 5/5
 ⠿ Network test_default          Created                                                                                                                                                                                                                                                      0.1s
 ⠿ Container test_db_1           Started                                                                                                                                                                                                                                                      1.0s
 ⠿ Container test_cli_1          Started                                                                                                                                                                                                                                                      1.1s
 ⠿ Container test_web_1          Started                                                                                                                                                                                                                                                      2.2s
 ⠿ Container test_cloudflared_1  Started                                                                                                                                                                                                                                                      0.8s
Connected vhost-proxy to "test_default" network.
Waiting for project stack to become ready...
Waiting for project stack to become ready...
ubuntu@testdocksal:~/projects/test$ fin share-v2 start
Replaced value for CLOUDFLARED_ENABLED in /home/ubuntu/projects/test/.docksal/docksal-local.env
Starting services...
[+] Running 4/4
 ⠿ Container test_cloudflared_1  Started                                                                                                                                                                                                                                                      0.9s
 ⠿ Container test_db_1           Running                                                                                                                                                                                                                                                      0.0s
 ⠿ Container test_cli_1          Running                                                                                                                                                                                                                                                      0.0s
 ⠿ Container test_web_1          Running                                                                                                                                                                                                                                                      0.0s
Project URL: http://test.docksal
Public URL: https://email-cable-monsters-correlation.trycloudflare.com
```

## First Attempt

URL: https://audience-arrivals-pending-favorite.trycloudflare.com

![image](https://user-images.githubusercontent.com/1564748/160337310-bae0be06-d25b-45a3-955c-d5254c05b270.png)

## Second Attempt

URL: https://email-cable-monsters-correlation.trycloudflare.com

![image](https://user-images.githubusercontent.com/1564748/160337353-56876423-130a-43e0-a359-9b2327dffa61.png)

**Comment by lmakarov** [comment]
Finally figured out what was going on.

macOS ships with an ancient bash v3.x.
I had bash updated on my Mac to the latest v5 via Homebrew. On Ubuntu, bash is also v5.
After I switched to the built-in bash version on Mac, I was able to reproduce the behavior that @sean-e-dietrich reported.

I had to refactor the way `load_configuration` works a bit and added tests.
This now works and was tested on macOS Intel/M1 and Ubuntu 20.04 Intel/ARM64.

**Review by sean-e-dietrich — APPROVED** [review]
I was able to confirm on Ubuntu Intel, Mac Intel/M1 that this works as intended

**Pull request merged**
