### PR TITLE
Added message that boot2docker needs to rebuild for 18.09 upgrade

### LINKED ISSUE #937: [BREAKING CHANGE] Update Docker versions
Update Docker versions to match the latest Docker Desktop:

- Docker 18.09.2
- Docker Machine 0.16.1

---

**BREAKING CHANGE**

`overlay2` is the default driver starting with boot2docker 18.09.0 and  Docker Desktop 18.06.0

AUFS support was deprecated in Docker/Boot2Docker [v18.06.0](https://github.com/boot2docker/boot2docker/releases/tag/v18.06.0-ce) and totally dropped in [v18.09.0](https://github.com/boot2docker/boot2docker/releases/tag/v18.09.0)+.

This is a breaking change, which requires the VM to be recreated from scratch. We will need to add a warning and a confirmation prompt during this update.

### PR DESCRIPTION
**Pull request by sean-e-dietrich**
The following update for Boot2Docker changes the underlying filesystem and requires the whole boot2docker system to be rebuilt. The following message warns users ahead of time.

Before we continue need to write blog post and link in code.

Closes #937 

---

Test updates from boot2docker 18.06 to 18.09 on:

  - [ ]  Mac
  - [ ]  Windows / Babun
  - [ ]  Windows / WSL

### CODE REVIEW

**Comment by lmakarov** [comment]
@sean-e-dietrich I added tests cases (in the description) that have to be handled manually to verify this works as expected.

Also, regarding Docker Desktop and Linux users - it's unclear what the flow would be there.

I believe, Docker Desktop gives a warning about the necessary VM rebuild, so that should be taken care of automatically.

Not sure what would happen on Linux. I think `overlay2` has been the default for quite a long time on Linux and there should be no instances using AUFS at this point. We can probably just ignore this case.

**Comment by sean-e-dietrich** [comment]
Tried to run the update and got the following error message:

```
Seans-MacBook-Pro:test sean$ DOCKSAL_VERSION=boot2docker_update fin update
[!] Using Docksal version: boot2docker_update
[STEP 1/6] Updating fin...
Password:
fin 1.82.2 downloaded...
 ALERT:  The following upgrade for Boot2Docker will require a complete rebuild.
         For more information see https://docs.docksal.io/troubleshooting/boot2docker-update/
Would you like to continue with the boot2docker upgrade? [y/n]: y
[STEP 2/6] Updating stack files...
overrides-ide.yml
overrides-osxfs.yml
services.yml
stack-acquia.yml
stack-default.yml
stack-default-nodb.yml
stack-node.yml
volumes-bind.yml
volumes-nfs.yml
volumes-none.yml
volumes-unison.yml
[STEP 3/6] Updating tools...
Remove docksal? [y/n]: y
About to remove docksal
WARNING: This action will delete both local reference and remote instance.
Successfully removed docksal
[STEP 4/6] Updating system images...
could not read CA certificate "/Users/sean/.docker/machine/machines/docksal/ca.pem": open /Users/sean/.docker/machine/machines/docksal/ca.pem: no such file or directory
could not read CA certificate "/Users/sean/.docker/machine/machines/docksal/ca.pem": open /Users/sean/.docker/machine/machines/docksal/ca.pem: no such file or directory
could not read CA certificate "/Users/sean/.docker/machine/machines/docksal/ca.pem": open /Users/sean/.docker/machine/machines/docksal/ca.pem: no such file or directory
Restoring network settings...
Configuring NFS shares...
Writing /etc/exports...
Restarting nfsd...
Mounting NFS shares...
Docker machine "docksal" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
Mounting local /Users to /Users
Docker machine "docksal" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
Retrying mounting local /Users to /Users
Docker machine "docksal" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
 ERROR:  NFS share mount failed.
         Try fin vm mount or fin vm restart.
Resetting Docksal system services...
 * proxy
could not read CA certificate "/Users/sean/.docker/machine/machines/docksal/ca.pem": open /Users/sean/.docker/machine/machines/docksal/ca.pem: no such file or directory
 ERROR:  Failed starting the proxy service.
Seans-MacBook-Pro:test sean$
```

**Comment by sean-e-dietrich** [comment]
After applying latest updates getting new message

```
Seans-MacBook-Pro:test sean$ DOCKSAL_VERSION=boot2docker_update fin update
[!] Using Docksal version: boot2docker_update
[STEP 1/6] Updating fin...
fin 1.82.2 downloaded...
 ALERT:  The following upgrade for Boot2Docker will require a complete rebuild.
         For more information see https://docs.docksal.io/troubleshooting/boot2docker-update/
Would you like to continue with the boot2docker upgrade? [y/n]: y
[STEP 2/6] Updating stack files...
overrides-ide.yml
overrides-osxfs.yml
services.yml
stack-acquia.yml
stack-default.yml
stack-default-nodb.yml
stack-node.yml
volumes-bind.yml
volumes-nfs.yml
volumes-none.yml
volumes-unison.yml
[STEP 3/6] Updating tools...
Remove docksal? [y/n]: y
About to remove docksal
WARNING: This action will delete both local reference and remote instance.
Successfully removed docksal
Creating docker machine 'docksal'...
Running pre-create checks...
Creating machine...
(docksal) Downloading /Users/sean/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v18.09.3/boot2docker.iso...
(docksal) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(docksal) Creating VirtualBox VM...
(docksal) Creating SSH key...
(docksal) Starting the VM...
(docksal) Check network to re-create if needed...
(docksal) Found a new host-only adapter: "vboxnet0"
(docksal) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env docksal
Starting "docksal"...
Machine "docksal" is already running.
 ERROR:  Failed starting virtual machine
```

**Comment by achekulaev** [comment]
Apparently `docker-machine` decided that starting already started machine is an error now... (facepalm icon)

```bash
11:05:37 ~/Projects/drupal8
§ fin dm start docksal
Starting "docksal"...
Machine "docksal" is already running.

11:05:45 ~/Projects/drupal8
§ echo $?
1
```

**Comment by achekulaev** [comment]
I'll fix it

**Comment by achekulaev** [comment]
This should fix it https://github.com/docksal/docksal/compare/7b7dfff4e3c5...efcbd7aed4b3
You need to rebase
Please also look at why tests are failing for `drush` provider

**Pull request closed without merging**
