### PR TITLE
WIP use mkcert for locally-trusted development certificates #498

### PR DESCRIPTION
**Pull request by fjmk**
In #498, [comment](https://github.com/docksal/docksal/issues/498#issuecomment-514158964) is mentioned that we could use [mkcert](https://github.com/FiloSottile/mkcert) for locally-trusted development certificates.

In this pull request I install mkcert, run 'mkcert -install' to create the locally-trusted CAROOT cerificate and create a site cerificate at 'fin project start'.
This certificate is trusted for $VIRTUAL_HOST as well as for *.$VIRTUAL_HOST.

TODOS:
Who can help me to install mkcert on windows and wsl?

- install_tools_wsl  
  Can I use $URL_MKCERT_NIX and MKCERT_BIN="/usr/local/bin/mkcert"
- install_tools_windows  
  Use $URL_MKCERT_WIN and what should MKCERT_BIN_WIN be?
- small change in [service-vhost-proxy](https://github.com/docksal/service-vhost-proxy) to redirect port 80 automatically to 443.

### CODE REVIEW

**Comment by achekulaev** [comment]
It seems that it could play better as an addon maybe? Like one where user would explicitly run `fin mkcert` or such, and only then have certificate generated for the project.

**Comment by lmakarov** [comment]
As much as I would like to have this streamlined for our users, automatically installing `mkcert` and creating a locally trusted CA may raise (valid) security concerns. This should be an optional step and require a consent from the user. 

I'm not yet sure whether this should go in core or be an addon. As an addon, it would have to be a global addon (not a project level addon), which I believe we intentionally do not support today. This may be the case to reconsider support for global addons.

**Comment by achekulaev** [comment]
We totally support global addons. Nothing wrong with them.

**Comment by lmakarov** [comment]
> We totally support global addons. Nothing wrong with them.

@achekulaev We support [global custom commands](https://docs.docksal.io/fin/custom-commands/#global-custom-commands), but not global addons. Addons are project specific and cannot be installed globally using `fin` today.

**Comment by achekulaev** [comment]
@lmakarov global addons will work if placed where they should be. Installation is a separate question.

**Comment by fjmk** [comment]
I understand your reservations.

I submitted an [addon mkcert](https://github.com/docksal/addons/pull/54) pull request with a lot of questions....

**Comment by lmakarov** [comment]
The addon is here: https://github.com/docksal/addons/tree/master/mkcert
Issue to include it in docs.docksal.io: https://github.com/docksal/docksal/issues/1370

**Pull request closed without merging**
