### PR TITLE
CarbonAds in docs

### PR DESCRIPTION
**Pull request by lmakarov**
- Added CarbonAds below search box
- Disabled AdSense via GTM (exclusivity requirement from CarbonAds)

Preview: https://deploy-preview-1472--docs-docksal-io.netlify.app/

### CODE REVIEW

**Comment by achekulaev** [comment]
Finally the monetizing solution to make us ritsch! 😅

**Comment by lmakarov** [comment]
ping @shelane

**Comment by shelane** [comment]
I'm seeing some strange layout issues in the menu area.
Screen Shot 2021-03-12 at 1 14 31 PM
That is on https://deploy-preview-1472--docs-docksal-io.netlify.app/fin/

**Comment by lmakarov** [comment]
I wish a had chops for frontend and styling. I'll see what I can do with this.

**Comment by shelane** [comment]
I have fallen more behind in those skills as well.

**Review by shelane — APPROVED** [review]

**Comment by lmakarov** [comment]
@shelane many thanks for the styling fix!

**Comment by shelane** [comment]
Credit goes to my colleague @jbernadas for the css fix.

**Pull request merged**
