### PR TITLE
Remove unneeded remote_connect_back configuration for Xdebug

### PR DESCRIPTION
**Pull request by lpeabody**
# Changes

- Removes unneeded `remote_connect_back` Xdebug configuration in recommended workaround for folks still on cli image version 2.12 and below.

### CODE REVIEW

**Review by shelane — APPROVED** [review]

**Review by lmakarov — CHANGES_REQUESTED** [review]
Let's just include `remote_host` (xdebug 2) along side `client_host` (xdebug 3) in `services.yml` for backward compatibility.

This way, there is nothing that the user has to do to switch between xdebug 2 and 3.

```
# Point xdebug to the listener on the host
# remote_host used by xdebug 2. client_host used by xdebug 3
XDEBUG_CONFIG=remote_host=${DOCKSAL_HOST_IP} client_host =${DOCKSAL_HOST_IP}
```

The section in the docs describing this change can then be dropped.

**Comment by lmakarov** [comment]
Let's also mention in the docs how to change the xdebug 3 `client_port` to `9003` if there is a need for that in a particular environment.


**docksal-local.yml**:

```
services:
    cli:
        environment:
            # xdebug 3 client endpoint settings
            - XDEBUG_CONFIG=client_host=${DOCKSAL_HOST_IP} client_port=9003
```

**Comment by shelane** [comment]
Looks like @lmakarov posted these (modified) updates in #1534. You can probably close this PR.

**Comment by lmakarov** [comment]
https://github.com/docksal/docksal/pull/1485#pullrequestreview-635819061 is still applicable. I'll submit another PR to incorporate it into the current state. Closing this one.

**Pull request closed without merging**
