### PR TITLE
Feature/proofreading

### PR DESCRIPTION
**Pull request by shelane**
Some spelling typos, missed commas, and periods.

Do you wish I'd stop reading your documentation for errors? Hey, I'm actually reading the documentation ;-)

### CODE REVIEW

**Comment by achekulaev** [comment]
https://www.dailywritingtips.com/comma-after-i-e-and-e-g/

> whether a comma follows [e.g.] or not is indifferent, or rather is decided by the punctuation-pitch of the writer of the passage

**Comment by shelane** [comment]
Ah, well I can point you to the tips that say that all except one style guide say to include the comma.

**Comment by shelane** [comment]
As an American, I tend to write with grammar to the style of American English, which includes spelling and punctuation. It's important to be consistent in whichever manner you go.

**Comment by achekulaev** [comment]
_>It's important to be consistent in whichever manner you go._
I guess before the fixes the manner was "no comma after e.g."

**Comment by shelane** [comment]
Except that in a previous pull request that was merged, all the docs were updated to use the comma ;-)

**Comment by achekulaev** [comment]
Yeah that's exactly what I meant saying "before the fix". I don't care enough about the "comma question" though, so I will merge this one too.
It was more a discussion for fun.

**Comment by shelane** [comment]
It’s all good. My issue is always to remove ambiguity where it may exist. If you would say it with a pause, a comma should be there.

**Comment by shelane** [comment]
I just wanted to share the sources I used before submitting my first changes. These are from very sources that I have used for many years:
https://www.quickanddirtytips.com/education/grammar/ie-versus-eg?page=1
https://www.grammarly.com/blog/know-your-latin-i-e-vs-e-g/
http://www.everythingenglishblog.com/?tag=comma-with-e-g

**Pull request merged**
