### PR TITLE
Adjusted Pull Command Variables

### PR DESCRIPTION
**Pull request by sean-e-dietrich**
Converted all provider pull variables to be lowercase and conform with other docksal options.

Also update documentation to account for these changes.

### CODE REVIEW

**Comment by sean-e-dietrich** [comment]
@lmakarov thanks! So added variable in travis `RUN_PULL_TESTS` that when set will run the pull tests.

**Comment by achekulaev** [comment]
@lmakarov Huston, we have a problem

Travis:
> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by lmakarov** [comment]
> Houston, we have a problem

Well, as I already mentioned, I believe `pull` commands should be moved into the `docksal/addons` repo and as separate addons, that can be tested independently. Might even need separate repos altogether for each of the hosting integrations.

**Comment by achekulaev** [comment]
Any other way to prolong execution time?

**Comment by sean-e-dietrich** [comment]
I'm thinking of cutting out the wp commands for now. Also all of starting/stopping for projects adds on probably about a couple of min for 29 tests. I added a variable that we test run_pull_tests I'm wondering if that is set then we don't run other tests. Similar to how the quicktests are set.

**Comment by achekulaev** [comment]
https://docs.travis-ci.com/user/speeding-up-the-build

**Comment by achekulaev** [comment]
@sean-e-dietrich nice work!

**Pull request merged**
