### PR TITLE
Allow setting shell and user to use when running `fin exec` and `fin bash` commands

### LINKED ISSUE #1107: Allow containers other than `cli` to use bash by default
**Description**

When trying to set up a docksal instance to simulate a decoupled site using different servers (Default stack with additional CLI for React/Node/Gatsby type) I noticed that in order to run commands like `fin exec --in=nodeapp yarn start` or `fin exec --in=nodeapp npm install` where `nodeapp` is the name of the service, I had to go through some significant hoops to get it to work.

**Steps to reproduce the issue:**

1. Add a second CLI based service to `docksal.yml`
2. Try to run a command in the service `fin exec --in=nodeapp npm install`

**Describe the results you received:**

`sh: 1: npm: not found`

**Describe the results you expected:**

Things to install

### PR DESCRIPTION
**Pull request by achekulaev**
- Introduces 2 new `io.docksal.shell` and `io.docksal.user` labels
- Documentation added

Closes #1107

### CODE REVIEW

**Comment by lmakarov** [comment]
Rebased onto develop (fixed tests in develop).

**Comment by achekulaev** [comment]
@lmakarov do you want to review the PR?

**Comment by lmakarov** [comment]
@achekulaev yes, at some point this week.

**Comment by lmakarov** [comment]
Rebased onto `develop` again to clear tests results. This test is failing (while `develop` builds are green):

```
not ok 9 fin exec
# (in test file /home/travis/build/docksal/docksal/tests/general.bats, line 199)
#   `[[ "$output" == "web" ]]' failed
# Status: 0
# Output:
# ================================================================
# unable to find user docker: no matching entries in passwd file
# ================================================================
```

**Comment by shelane** [comment]
I have some documentation updates for the page added here. Let me know when I can add to this branch.

**Comment by shelane** [comment]
Actually, I added the commit to feature/pick-container-shell-documentation if you want to cherry pick it. I'm not going to be reachable in a bit.

**Comment by achekulaev** [comment]
@shelane make a different PR please later

**Pull request merged**
